### PR TITLE
Delete Spark datasource

### PR DESCRIPTION
**Pull request by ykmr1224**
### Description
Delete Spark datasource related classes since it is no longer used.
 
### Issues Resolved
N/A
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass, including unit test, integration test and doctest
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
  - [ ] New functionality has user manual doc added
- [ ] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by vamsi-amazon** [comment]
can we also rename the module to async-query-api probably..or whatever is best.

**Comment by ykmr1224** [comment]
> * can we also rename the module to async-query-api probably..or whatever is best.
I am thinking to rename the module once all the refactoring is done together with the module split.

> * probably need to update documentation if there is anything for spark datasource.
I see only see `spark: Spark storage engine` in DEVELOPER_GUIDE.rst. Let me fix it together with package name change and split.

**Comment by vamsi-amazon** [comment]
@ykmr1224  can you look into build errors in CI.

**Comment by vamsi-amazon** [comment]
https://github.com/opensearch-project/sql/blob/main/docs/user/ppl/admin/connectors/spark_connector.rst
This rst file is not required anymore.

**Comment by ykmr1224** [comment]
Fixed the coverage issue, and deleted spark_connector.rst

**Comment by ykmr1224** [comment]
Fixed another coverage issue.

**Review by seankao-az — APPROVED** [review]

**Review by vamsi-amazon — APPROVED** [review]

**Pull request merged**
