### PR TITLE
Add release notes for v2.18.0

### PR DESCRIPTION
**Pull request by dai-chen**
### Description

Add release notes for OpenSearch 2.18.0 release.

### Related Issues

https://github.com/opensearch-project/sql/issues/3000

### Check List

- [x] Commits are signed per the DCO using `--signoff`.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/sql/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by dai-chen** [comment]
BWC failed.

**Review by Swiddis — APPROVED** [review]
Would be nice to remove all the [backport] prefixes

**Comment by Swiddis** [comment]
BWC failures discussed in #3089

**Comment by dai-chen** [comment]
> Would be nice to remove all the [backport] prefixes

Sure, resolved in https://github.com/opensearch-project/sql/pull/3125/commits/fdb0a0abf84ee19b8a0e2e0c76def5f267852113. Thanks!

**Review by noCharger — APPROVED** [review]

**Review by seankao-az — APPROVED** [review]

**Review by Swiddis — APPROVED** [review]

**Pull request merged**
