### PR TITLE
Incremented version to 1.3.4.

### PR DESCRIPTION
**Pull request by zelinh**
Signed-off-by: Zelin Hao <zelinhao@amazon.com>

### Description
Increment version to 1.3.4
 
### Issues Resolved
Part of https://github.com/opensearch-project/opensearch-build/issues/2205
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass, including unit test, integration test and doctest
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
  - [ ] New functionality has user manual doc added
- [ ] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by zelinh** [comment]
We will need to get [this one](https://github.com/opensearch-project/ml-commons/pull/359) in first to unblock this PR.

**Review by joshuali925 — DISMISSED** [review]
approving first, might need some time for CI to be able to pass

**Review by kavithacm — APPROVED** [review]

**Comment by kavithacm** [comment]
CI is failing, re-running the failed jobs

**Comment by zelinh** [comment]
We are re-triggering the build with ml-commons artifacts in; should be having it after.

**Review by joshuali925 — APPROVED** [review]
not sure if my approval counts since i pushed changes

might be easier if version bumps of dependent plugins are prioritized so we get more time to fix those errors

**Review by kavithacm — APPROVED** [review]

**Pull request merged**
