### PR TITLE
Remove BWC tests

### PR DESCRIPTION
**Pull request by Yury-Fridlyand**
Remove backward compatibility (BWC) tests with `OpenDistro` from GitHub Actions (GHA), because `OpenDistro` was archived and not available anymore for testing.
https://opendistro.github.io/for-elasticsearch/blog/2022/08/Open-Distro-is-archived/

Signed-off-by: Yury Fridlyand <yuryf@bitquilltech.com>

### Issues Resolved
Failing GHA
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass, including unit test, integration test and doctest
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
  - [ ] New functionality has user manual doc added
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by joshuali925** [comment]
BWC test will still be needed for opensearch? like OS1.0 to OS2.0

**Review by acarbonetto — DISMISSED** [review]

**Review by acarbonetto — APPROVED** [review]

**Comment by dai-chen** [comment]
Approving to unblock other failed PR for now. But not sure if we should do this the other way around (un-archive the ODFE repo). Because I recall we need to patch ODFE sometimes, archived repo blocks code merge.

**Review by dai-chen — APPROVED** [review]
Thanks for the fix!

**Review by joshuali925 — APPROVED** [review]
probably not needed to change script permission but ok

**Comment by joshuali925** [comment]
> Approving to unblock other failed PR for now. But not sure if we should do this the other way around (un-archive the ODFE repo). Because I recall we need to patch ODFE sometimes, archived repo blocks code merge.

we don't need to patch ODFE anymore as it reached EOL, but we should remove ODFE related BWC tests while keep BWC framework for OpenSearch

**Comment by dblock** [comment]
+1 to @joshuali925, removing bcw tests seems like an undesirable effect 

If you agee @Yury-Fridlyand, care to open an issue to restore the bcw tests against supported versions of OpenSearch?

**Comment by Yury-Fridlyand** [comment]
Sure. We can start testing upgrade scenario 1.x -> 2.x.

**Comment by dblock** [comment]
I opened https://github.com/opensearch-project/sql/issues/733

**Pull request merged**
