### PR TITLE
Update opensearch-sql.release-notes-2.13.0.0.md to conform with OpenSearch guidelines

### PR DESCRIPTION
**Pull request by rupal-bq**
### Description
- Updated opensearch-sql.release-notes-2.13.0.0.md to conform with OpenSearch guidelines
 
### Issues Resolved
https://github.com/opensearch-project/sql/issues/2599
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass, including unit test, integration test and doctest
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
  - [ ] New functionality has user manual doc added
- [ ] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by YANG-DB — APPROVED** [review]

**Comment by noCharger** [comment]
Thanks for the change! Is it possible to create a GitHub action to generate release notes automatically?

**Review by noCharger — APPROVED** [review]

**Comment by rupal-bq** [comment]
> Thanks for the change! Is it possible to create a GitHub action to generate release notes automatically?

There are some examples based on PR labels but didn't explore much on this.

**Comment by gaiksaya** [comment]
There are some suggestion for automation here: https://github.com/opensearch-project/opensearch-plugins/blob/main/RELEASE_NOTES.md#automation

**Comment by rupal-bq** [comment]
created https://github.com/opensearch-project/sql/issues/2610 to track release notes automation.

**Review by vamsi-amazon — APPROVED** [review]

**Comment by vamsi-amazon** [comment]
Thanks for the changes.

**Pull request merged**
