### PR TITLE
[Manual Backport] Backport doctest fix to 2.x

### PR DESCRIPTION
**Pull request by Swiddis**
### Description
Backport of #3053

### Related Issues
N/A

### Check List
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
 - [ ] New functionality has javadoc added.
 - [ ] New functionality has a user manual doc added.
- [ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md).
- [X] Commits are signed per the DCO using `--signoff`.
- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose).

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/sql/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by noCharger — COMMENTED** [review]
```

> Task :sql:jacocoTestReport
FAILURE: Build failed with an exception.

> Task :sql:check
* What went wrong:
Execution failed for task ':integ-test:integTest'.
> There were failing tests. See the report at: file:///__w/sql/sql/integ-test/build/reports/tests/integTest/index.html
```

Does any other PR fix this?

**Comment by Swiddis** [comment]
#3084

**Comment by noCharger** [comment]
> #3084

@Swiddis  since this one is merged, could you rebase and verify doctest passed?

**Comment by Swiddis** [comment]
Additionally copied import fix from #3113

**Comment by Swiddis** [comment]
Nvm, #3113's broken PR wasn't backported yet so we don't need the import fix here

**Review by noCharger — APPROVED** [review]

**Review by penghuo — APPROVED** [review]

**Pull request merged**
