### PR TITLE
Do not remove opensearch from the list of registered catalogs.

### LINKED ISSUE #866: [BUG] Plugin returns `NullPointerException` for any query after a specific one
## What is the bug?
SQL returns `NullPointerException` to any query in some condition.

### 1. Run a valid SQL query - get a valid answer
```
opensearchsql> select COUNT(*) from `beer.stackexchange`;
fetched rows / total rows = 1/1
+------------+
| COUNT(*)   |
|------------|
| 60         |
+------------+
```

### 2. Run a valid PPL query - get an error
```
opensearchsql> source=beer.stackexchange | where multi_match([Title, Body, Tags], 'hops');
{'reason': 'Invalid Query', 'details': '', 'type': 'NullPointerException'}
```
<details>
<summary>Exception stack</summary>

```
Error happened during query handling
java.lang.NullPointerException: null
        at org.opensearch.sql.analysis.Analyzer.visitRelation(Analyzer.java:130) ~[core-2.4.0.0-SNAPSHOT.jar:?]
        at org.opensearch.sql.analysis.Analyzer.visitRelation(Analyzer.java:92) ~[core-2.4.0.0-SNAPSHOT.jar:?]
        at org.opensearch.sql.ast.tree.Relation.accept(Relation.java:105) ~[core-2.4.0.0-SNAPSHOT.jar:?]
        at org.opensearch.sql.analysis.Analyzer.visitFilter(Analyzer.java:169) ~[core-2.4.0.0-SNAPSHOT.jar:?]
        at org.opensearch.sql.analysis.Analyzer.visitFilter(Analyzer.java:92) ~[core-2.4.0.0-SNAPSHOT.jar:?]
        at org.opensearch.sql.ast.tree.Filter.accept(Filter.java:44) ~[core-2.4.0.0-SNAPSHOT.jar:?]
        at org.opensearch.sql.analysis.Analyzer.visitProject(Analyzer.java:288) ~[core-2.4.0.0-SNAPSHOT.jar:?]
        at org.opensearch.sql.analysis.Analyzer.visitProject(Analyzer.java:92) ~[core-2.4.0.0-SNAPSHOT.jar:?]
        at org.opensearch.sql.ast.tree.Project.accept(Project.java:71) ~[core-2.4.0.0-SNAPSHOT.jar:?]
        at org.opensearch.sql.analysis.Analyzer.analyze(Analyzer.java:115) ~[core-2.4.0.0-SNAPSHOT.jar:?]
        at org.opensearch.sql.ppl.PPLService.plan(PPLService.java:89) ~[ppl-2.4.0.0-SNAPSHOT.jar:?]
        at org.opensearch.sql.ppl.PPLService.execute(PPLService.java:59) [ppl-2.4.0.0-SNAPSHOT.jar:?]
        at org.opensearch.sql.plugin.transport.TransportPPLQueryAction.doExecute(TransportPPLQueryAction.java:93) [opensearch-sql-2.4.0.0-SNAPSHOT.jar:2.4.0.0-SNAPSHOT]
        at org.opensearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:218) [opensearch-2.4.0-SNAPSHOT.jar:2.4.0-SNAPSHOT]
        at org.opensearch.action.support.TransportAction.execute(TransportAction.java:188) [opensearch-2.4.0-SNAPSHOT.jar:2.4.0-SNAPSHOT]
        at org.opensearch.action.support.TransportAction.execute(TransportAction.java:107) [opensearch-2.4.0-SNAPSHOT.jar:2.4.0-SNAPSHOT]
        at org.opensearch.client.node.NodeClient.executeLocally(NodeClient.java:110) [opensearch-2.4.0-SNAPSHOT.jar:2.4.0-SNAPSHOT]
        at org.opensearch.client.node.NodeClient.doExecute(NodeClient.java:97) [opensearch-2.4.0-SNAPSHOT.jar:2.4.0-SNAPSHOT]
        at org.opensearch.client.support.AbstractClient.execute(AbstractClient.java:426) [opensearch-2.4.0-SNAPSHOT.jar:2.4.0-SNAPSHOT]
        at org.opensearch.sql.plugin.rest.RestPPLQueryAction.lambda$prepareRequest$2(RestPPLQueryAction.java:117) [opensearch-sql-2.4.0.0-SNAPSHOT.jar:2.4.0.0-SNAPSHOT]
        at org.opensearch.sql.opensearch.executor.Scheduler.lambda$withCurrentContext$0(Scheduler.java:30) [opensearch-2.4.0.0-SNAPSHOT.jar:?]
        at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:747) [opensearch-2.4.0-SNAPSHOT.jar:2.4.0-SNAPSHOT]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
```
</details>

### 3. Run SQL query again - get a error ❗ 
```
opensearchsql> select COUNT(*) from `beer.stackexchange`;
{'reason': 'Invalid SQL query', 'details': '', 'type': 'NullPointerException'}
```
<details>
<summary>Exception stack</summary>

```
Client side error during query execution
java.lang.NullPointerException: null
        at org.opensearch.sql.analysis.Analyzer.visitRelation(Analyzer.java:130) ~[core-2.4.0.0-SNAPSHOT.jar:?]
        at org.opensearch.sql.analysis.Analyzer.visitRelation(Analyzer.java:92) ~[core-2.4.0.0-SNAPSHOT.jar:?]
        at org.opensearch.sql.ast.tree.Relation.accept(Relation.java:105) ~[core-2.4.0.0-SNAPSHOT.jar:?]
        at org.opensearch.sql.analysis.Analyzer.visitAggregation(Analyzer.java:212) ~[core-2.4.0.0-SNAPSHOT.jar:?]
        at org.opensearch.sql.analysis.Analyzer.visitAggregation(Analyzer.java:92) ~[core-2.4.0.0-SNAPSHOT.jar:?]
        at org.opensearch.sql.ast.tree.Aggregation.accept(Aggregation.java:76) ~[core-2.4.0.0-SNAPSHOT.jar:?]
        at org.opensearch.sql.analysis.Analyzer.visitProject(Analyzer.java:288) ~[core-2.4.0.0-SNAPSHOT.jar:?]
        at org.opensearch.sql.analysis.Analyzer.visitProject(Analyzer.java:92) ~[core-2.4.0.0-SNAPSHOT.jar:?]
        at org.opensearch.sql.ast.tree.Project.accept(Project.java:71) ~[core-2.4.0.0-SNAPSHOT.jar:?]
        at org.opensearch.sql.analysis.Analyzer.analyze(Analyzer.java:115) ~[core-2.4.0.0-SNAPSHOT.jar:?]
        at org.opensearch.sql.sql.SQLService.analyze(SQLService.java:97) ~[sql-2.4.0.0-SNAPSHOT.jar:?]
        at org.opensearch.sql.legacy.plugin.RestSQLQueryAction.prepareRequest(RestSQLQueryAction.java:110) ~[legacy-2.4.0.0-SNAPSHOT.jar:?]
        at org.opensearch.sql.legacy.plugin.RestSqlAction.lambda$prepareRequest$1(RestSqlAction.java:158) [legacy-2.4.0.0-SNAPSHOT.jar:?]
        at org.opensearch.sql.opensearch.executor.Scheduler.lambda$withCurrentContext$0(Scheduler.java:30) [opensearch-2.4.0.0-SNAPSHOT.jar:?]
        at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:747) [opensearch-2.4.0-SNAPSHOT.jar:2.4.0-SNAPSHOT]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:829) [?:?]
```
</details>

## What is the expected behavior?
1. No error on valid queries
2. No context/data/whatever persist after a query or shared between queries

## What is your host/environment?
`2.x` @ 10e44ee

## Do you have any additional context?
Workaround - restart server

### PR DESCRIPTION
**Pull request by MaxKsyunz**
Signed-off-by: MaxKsyunz <maxk@bitquilltech.com>

### Description
A simple fix for a simple bug -- indices with a period in the name can only be queried once.
 
### Issues Resolved
#866 
 
### Check List
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by dai-chen — DISMISSED** [review]
Thanks for the fix! Could you add UT in `CatalogServiceImplTest`?

**Review by vamsi-amazon — DISMISSED** [review]

**Comment by vamsi-amazon** [comment]
Thanks for the fix. somehow didn't caught this in testing.

**Comment by dai-chen** [comment]
> Thanks for the fix. somehow missed this in testing. Was wondering how did doctest miss this failure as it executes multiple queries.

As I understand, this problem only happens for index name with dot in middle. Othewise, `catalogName` will be null in the first place and `getCatalogs()` method call won't be triggered due to short circuit.

```
    if (catalogName != null && !catalogService.getCatalogs().contains(catalogName)) {
      tableName = catalogName + "." + tableName;
      catalogName = null;
    }
```

**Comment by vamsi-amazon** [comment]
Can we close this PR in favour of https://github.com/opensearch-project/sql/pull/870/files

**Comment by MaxKsyunz** [comment]
> Can we close this PR in favour of https://github.com/opensearch-project/sql/pull/870/files
> 
> I am not sure if I have permissions to push changes on bitquill repo.
> 
> @MaxKsyunz @dai-chen Made few more changes and included ITs.

Yup!

**Pull request closed without merging**
