### PR TITLE
update codeowners and maintainers

### PR DESCRIPTION
**Pull request by derek-ho**
### Description
Baseline repo maintainers and codeowners
 
### Issues Resolved
fix: #1337 
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass, including unit test, integration test and doctest
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
  - [ ] New functionality has user manual doc added
- [ ] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by anirudha — APPROVED** [review]

**Review by YANG-DB — APPROVED** [review]

**Review by MaxKsyunz — APPROVED** [review]

**Comment by MaxKsyunz** [comment]
@derek-ho This PR needs to be backported to 2.x so that the new code owners are treated as such in the 2.x branch.

**Comment by bbarani** [comment]
Please DO NOT merge until CODOWNERS file turns green.

**Comment by bbarani** [comment]
Its ready to merge. CODEOWNERS is green as I have added the maintainers.

**Comment by MaxKsyunz** [comment]
> This PR should not be ideally merged until CODEOWNERS file turns green.
I didn't realize that, @bbarani. Will know for next time.

**Pull request merged**
