### PR TITLE
Fix error messaging from prometheus.

### PR DESCRIPTION
**Pull request by vamsi-amazon**
Signed-off-by: vamsi-amazon <reddyvam@amazon.com>

### Description
* Improved messaging from prometheus response.

 
### Issues Resolved
[List any issues this PR will resolve]
 
### Check List
- [x] New functionality includes testing.
  - [ ] All tests pass, including unit test, integration test and doctest
- [x] New functionality has been documented.
  - [ ] New functionality has javadoc added
  - [ ] New functionality has user manual doc added
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by dai-chen** [comment]
Have you confirmed if 30 and 90 days' windowing is equivalent to month and quarter in Prometheus? It seems not in our span implementation. For example, `span by 1 month` is expected to window the result month by month exactly. However, `span by 30 days` may give you window start time Jan 3 or Feb 4, because month is not fixed window size like second/minute/hour. If it's the same in Prometheus, rather than converting them, we should not push down in this case.

**Comment by vamsi-amazon** [comment]
Prometheus doesn't support month and quarter

**Comment by vamsi-amazon** [comment]
Are you suggesting to not push down in case month or quarter provided

**Comment by dai-chen** [comment]
> Are you suggesting to not push down in case month or quarter provided

Yes, either do it in post-processing or throw unsupported exception. Otherwise it would be confusing user.

**Review by dai-chen — APPROVED** [review]
The response body is just what Prometheus returns to us with error details, right? Just want to double check there is no security concern here. Thanks!

**Comment by vamsi-amazon** [comment]
> The response body is just what Prometheus returns to us with error details, right? Just want to double check there is no security concern here. Thanks!

Yes.

**Review by sejli — APPROVED** [review]

**Review by derek-ho — APPROVED** [review]

**Pull request merged**
