### PR TITLE
chore: Update Spring to 5.3.39

### PR DESCRIPTION
**Pull request by Swiddis**
### Description
Update Spring to latest patch to quiet CVE scanners.

### Related Issues
N/A

### Check List
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
 - [ ] New functionality has javadoc added.
 - [ ] New functionality has a user manual doc added.
- [ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md).
- [ ] Commits are signed per the DCO using `--signoff`.
- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose).

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/sql/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by dai-chen — COMMENTED** [review]
Is CI failure related?

**Comment by Swiddis** [comment]
Shouldn't be, I was getting issues with finding Nebula locally even before making the change. Old PRs on this branch have their logs out of the retainment window so not sure if this is precedent.

**Review by noCharger — COMMENTED** [review]
Does this fix applicable? https://github.com/opensearch-project/sql/pull/3177

**Comment by dai-chen** [comment]
Just to confirm, our `main` and `2.x` doesn't have this issue right? Because I notice this PR is targeting `1.x` directly.

**Comment by Swiddis** [comment]
2.x seems to be failing for different reasons https://github.com/opensearch-project/sql/actions/runs/12042222533/job/33575506240

But this is just to quiet CVE scanners complaining about the outdated dep on 1.x, the changelog between the spring versions is negligible

**Comment by Swiddis** [comment]
> Does this fix applicable? #3177
> 
> Saw CI failed on
> 
> ```
> Run actions/upload-artifact@v4
> With the provided path, there will be [1](https://github.com/opensearch-project/sql/actions/runs/12167741795/job/33936977780?pr=3187#step:6:1) file uploaded
> Artifact name is valid!
> Root directory input is valid!
> Error: Failed to CreateArtifact: Received non-retryable error: Failed request: (409) Conflict: an artifact with this name already exists on the workflow run
> ```

Went away after rerunning -- maybe conflicted with the last job run since I also pushed the upload-artifact fix fairly quickly

**Review by noCharger — APPROVED** [review]

**Review by dai-chen — APPROVED** [review]
Please confirm if CI failure is related or not.

**Comment by Swiddis** [comment]
CI isn't related, can track that as a separate task if needed

**Pull request merged**
