### PR TITLE
Incremented version to 1.3.2.

### PR DESCRIPTION
**Pull request by zelinh**
Signed-off-by: Zelin Hao <zelinhao@amazon.com>

### Description
Incremented version to 1.3.2.
 
### Issues Resolved
Part of https://github.com/opensearch-project/opensearch-build/issues/1882
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass, including unit test, integration test and doctest
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
  - [ ] New functionality has user manual doc added
- [ ] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by joshuali925** [comment]
ml artifact (https://github.com/zelinh/sql/blob/increment-to-1.3.2/doctest/resources/ml-commons/opensearch-ml-1.3.1.0-SNAPSHOT.zip) should be 1.3.2? also this seems to be a duplicate of #526

**Comment by zelinh** [comment]
We just added `ml-commons` to our CI manifest. Should be getting the snapshot artifacts after build.

**Comment by zelinh** [comment]
@joshuali925 
It seems like the CI tests fetch the ml artifacts from the old URL `https://ci.opensearch.org/ci/dbc/distribution-build-opensearch/1.3.2/latest/linux/x64/builds/opensearch/plugins/opensearch-ml-1.3.2.0.zip`
and missed the additional `tar` folder.
The new CI link should be `https://ci.opensearch.org/ci/dbc/distribution-build-opensearch/1.3.2/latest/linux/x64/tar/builds/opensearch/plugins/opensearch-ml-1.3.2.0.zip`

**Comment by joshuali925** [comment]
updated your branch @zelinh

**Review by joshuali925 — APPROVED** [review]

**Comment by zelinh** [comment]
@joshuali925 Could you help rerun the failed test? Seems like a connection error. 
```
Run actions/setup-node@v1
Unexpected HTTP response: 500
Waiting [10](https://github.com/opensearch-project/sql/runs/6263744512?check_suite_focus=true#step:4:10) seconds before trying again
Unexpected HTTP response: 500
Waiting 15 seconds before trying again
Error: Unexpected HTTP response: 500
```

**Review by vamsi-amazon — APPROVED** [review]

**Pull request merged**
