### PR TITLE
Fix: Misc typo and broken link fixes

### PR DESCRIPTION
**Pull request by andy-k-improving**
### Description
Some typo / broken link fixes on documentation.

### Related Issues
N/A

### Check List
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
 - [ ] New functionality has javadoc added.
 - [ ] New functionality has a user manual doc added.
- [ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md).
- [x] Commits are signed per the DCO using `--signoff`.
- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose).

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/sql/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by andy-k-improving** [comment]
Hi @noCharger @dai-chen 
would you guys mind to have a look on this one.
Your help would be appreciated!

**Review by dai-chen — APPROVED** [review]
Thanks for the fix!

**Review by ykmr1224 — APPROVED** [review]
Thanks!

**Review by noCharger — APPROVED** [review]

**Comment by andy-k-improving** [comment]
Hi @dai-chen @noCharger @ykmr1224 I see there is a integration test failure on the CI run, but there is no code change on my submission.
May be that is flaky test perhaps?

**Review by YANG-DB — APPROVED** [review]

**Pull request merged**
