### PR TITLE
Release Notes for 2.7.0

### PR DESCRIPTION
**Pull request by vamsi-amazon**
### Description
Release Notes for 2.7.0
 
### Issues Resolved
[List any issues this PR will resolve]
 
### Check List
- [x] New functionality includes testing.
  - [ ] All tests pass, including unit test, integration test and doctest
- [x] New functionality has been documented.
  - [ ] New functionality has javadoc added
  - [ ] New functionality has user manual doc added
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by Yury-Fridlyand** [comment]
@anirudha pagination?

**Review by YANG-DB — APPROVED** [review]
Didn't we add a GH workflow to auto generate the release notes...

**Comment by vamsi-amazon** [comment]
> @anirudha pagination?

@Yury-Fridlyand  are there any pending PRs to be merged?

**Comment by vamsi-amazon** [comment]
> Didn't we add a GH workflow to auto generate the release notes...

Not sure, I manually generated. Simeone can confirm this.

**Review by dai-chen — APPROVED** [review]
Thanks!

**Comment by Yury-Fridlyand** [comment]
> 
> @Yury-Fridlyand are there any pending PRs to be merged?

#1497

**Review by rupal-bq — APPROVED** [review]

**Review by Yury-Fridlyand — APPROVED** [review]

**Pull request merged**
