### PR TITLE
Add spark applicationId

### PR DESCRIPTION
**Pull request by rupal-bq**
### Description
- Added applicationId 
 
### Issues Resolved
https://github.com/opensearch-project/sql/issues/1722
- applicationId will be used instead of stepId for non-emr spark setup
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass, including unit test, integration test and doctest
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
  - [ ] New functionality has user manual doc added
- [ ] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by Yury-Fridlyand** [comment]
Is it possible to do an IT for that?

**Comment by rupal-bq** [comment]
> Is it possible to do an IT for that?

Need to check. will address that in follow up PR.

**Comment by dai-chen** [comment]
Could you elaborate a little what's the difference and why this change?

**Comment by rupal-bq** [comment]
> Could you elaborate a little what's the difference and why this change?

In spark connector, we will be able to use different spark clients. In case of EMR client, stepId can be used to fetch the result from opensearch index but stepId concept is specific to EMR.

So when we will use another client e.g. Livy client then we can use spark applicationId to get results from opensearch index because Livy response includes appId.
ref: https://livy.incubator.apache.org/docs/latest/rest-api.html

This is basically just for adding alternate option to stepId if it's not emr in design of https://github.com/opensearch-project/sql/issues/1722

**Review by penghuo — APPROVED** [review]

**Review by dai-chen — APPROVED** [review]

**Pull request merged**
