### PR TITLE
change plugin folder name to opensearch-sql

### LINKED ISSUE #660: [BUG] Configure project name for gradle subproject in `plugin/` folder.
**What is the bug?**
Add `settings.gradle` file and configure the project name as `opensearch-sql` in `plugin/` folder.

**What is the expected behavior?**
To have a project name for gradle project residing inside the `plugin/` folder https://github.com/opensearch-project/sql/tree/main/plugin

**Do you have any additional context?**
Without the project name the plugin zips being published with `artifactID` as `plugin` https://aws.oss.sonatype.org/content/repositories/snapshots/org/opensearch/plugin/plugin/, this does not add a proper naming convention and does not represent as sql plugin zip.

### PR DESCRIPTION
**Pull request by kavithacm**
Signed-off-by: Kavitha Conjeevaram Mohan <mohakavi@amazon.com>

### Description
Changing sql/plugin folder name to sql/opensearch-sql to fix getting unknown plugin error in OpenSearch maven build. This change provides name to sql plugin when built in opensearch

Update: changing plugin name didn’t work so adding settings.gradle file to plugin folder

### Issues Resolved
closes #660 
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass, including unit test, integration test and doctest
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
  - [ ] New functionality has user manual doc added
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by joshuali925 — DISMISSED** [review]
could you also port this PR to main

**Review by mengweieric — APPROVED** [review]

**Comment by kavithacm** [comment]
testing the build locally. once its successful i'll reopen the PR

**Review by joshuali925 — APPROVED** [review]
could you also change `:plugin` in https://github.com/opensearch-project/sql/blob/main/DEVELOPER_GUIDE.rst#opensearch-opensearch-dashboards

**Review by vamsi-amazon — APPROVED** [review]

**Review by acarbonetto — APPROVED** [review]
LGTM

**Comment by prudhvigodithi** [comment]
LGTM
` /gradlew properties` lists `opensearch-sql-plugin` 
```
allprojects: [root project 'opensearch-sql', project ':common', project ':core', project ':doctest', project ':integ-test', project ':legacy', project ':opensearch', project ':opensearch-sql-plugin', project ':ppl', project ':protocol', project ':sql']
```

**Pull request merged**
