### PR TITLE
[Backport 2.17] Fix handler for existing query (#2968)

### PR DESCRIPTION
**Pull request by ykmr1224**
### Description
- backport #2968 to 2.17 (auto backport failed)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/sql/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by seankao-az** [comment]
why did auto backport fail?

**Review by seankao-az — APPROVED** [review]

**Comment by ykmr1224** [comment]
> why did auto backport fail?

Due to conflict

**Review by vamsi-amazon — DISMISSED** [review]

**Review by seankao-az — APPROVED** [review]

**Comment by seankao-az** [comment]
Can we check CI for this? Not bwc test failure

**Comment by ykmr1224** [comment]
Closing as I was able to make auto backport: https://github.com/opensearch-project/sql/pull/2983

**Pull request closed without merging**
