### PR TITLE
Remove workbench and its workflows

### PR DESCRIPTION
**Pull request by kavithacm**
### Description
Removing workbench and its workflows from SQL repository 1.3 branch to reduce unwanted CVE advisories for this branch

### Issues Resolved
[List any issues this PR will resolve]
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass, including unit test, integration test and doctest
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
  - [ ] New functionality has user manual doc added
- [ ] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by derek-ho — DISMISSED** [review]

**Comment by YANG-DB** [comment]
please fix the links in the README.md file pointing to the deleted folder

**Review by YANG-DB — CHANGES_REQUESTED** [review]
plz fix links from README.md pointing to deleted files

**Comment by dai-chen** [comment]
Does this mean all future SQL Workbench release should happen in the new repo? If so, we should remove it from all .x branch? Same for other clients code?

**Comment by kavithacm** [comment]
> 

This change is only required for 1.3 branch workbench as it has CVEs, future releases for 1.3 branch should be done in new repo for workbench.

**Comment by kavithacm** [comment]
> > > 
> > 
> > 
> > This change is only required for 1.3 branch workbench as it has CVEs, future releases for 1.3 branch should be done in new repo for workbench.
> 
> Does Workbench code in 1.x branch have the fix? If not, I think we should remove at least 1.x along with 1.3. Otherwise, future branch 1.4, 1.5 will have same CVE?

I agree, if 1.x doesn't have the CVE fix, we should remove it there too. Currently we're focusing on 1.3 branch as there's a release this week

**Review by YANG-DB — APPROVED** [review]

**Review by pjfitzgibbons — APPROVED** [review]

**Pull request merged**
