### PR TITLE
Two single or double quote escapes single or double quote when string is surrounded by same type of quote

### PR DESCRIPTION
**Pull request by MitchellGale-BitQuill**
### Description
Adds implementation for double quotes working to escape a single quote.

Uses string builder to generate query in `String Utils`. Only escapes quote when outside quotes are matching, does not work for `. Below are examples of how the new queries function.

```
SELECT 'I''m';          -> I'm
SELECT 'I''''m';        -> I''m
SELECT "I''m";          -> I''m
SELECT "I""m";          -> I"m
SELECT \`I\`\`m\`;      -> I``m
SELECT 'I""''m';        -> I""'m
```
 
### Issues Resolved
[[Issue #682]](https://github.com/opensearch-project/sql/issues/682) 

### Check List
- [x] New functionality includes testing.
  - [x] All tests pass, including unit test, integration test and doctest
- [x] New functionality has been documented.
  - [x] New functionality has javadoc added
  - [x] New functionality has user manual doc added
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by joshuali925 — APPROVED** [review]
lgtm

**Comment by penghuo** [comment]
could you add docs to explain the unquote also?

**Comment by Yury-Fridlyand** [comment]
Please, fix code style:
```
Error: [checkstyle] [ERROR] /home/runner/work/sql/sql/common/src/main/java/org/opensearch/sql/common/utils/StringUtils.java:30: Line is longer than 100 characters (found 114). [LineLength]
Error: [checkstyle] [ERROR] /home/runner/work/sql/sql/common/src/main/java/org/opensearch/sql/common/utils/StringUtils.java:31: Line is longer than 100 characters (found 109). [LineLength]
```

**Review by mengweieric — APPROVED** [review]

**Comment by dai-chen** [comment]
> could you add docs to explain the unquote also?

+1. Probably can add here: https://github.com/opensearch-project/sql/blob/main/docs/user/general/datatypes.rst#string-data-types

**Pull request merged**
