### PR TITLE
Boolean function in PPL should be case insensitive

### PR DESCRIPTION
**Pull request by LantaoJin**
### Description
`isnotnull()` works but `ISNOTNULL()` doesn't work in PPL.
 
### Issues Resolved
Resolve https://github.com/opensearch-project/sql/issues/2431
 
### Check List
- [x] New functionality includes testing.
  - [x] All tests pass, including unit test, integration test and doctest
- ~~[ ] New functionality has been documented.~~
  - ~~[ ] New functionality has javadoc added~~
  - ~~[ ] New functionality has user manual doc added~~
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by penghuo — APPROVED** [review]
Thx!

**Review by dai-chen — APPROVED** [review]
Thanks for the fix!

**Comment by LantaoJin** [comment]
Thanks for your reviewing @penghuo @dai-chen @vamsi-amazon , will this PR be merged automatically? Any action should I do next?

**Comment by vamsi-amazon** [comment]
@LantaoJin Could you confirm if the build issues are not because of your commit. I will merge all the approved PRs.

**Comment by LantaoJin** [comment]
> @LantaoJin Could you confirm if the build issues are not because of your commit. I will merge all the approved PRs.
> 
> 

None of current build issues caused by this code changes.

**Review by dai-chen — APPROVED** [review]
Approved. I think you can merge from `main` to fix CI now.

**Pull request merged**
