### PR TITLE
Adding new maintainer @noCharger

### PR DESCRIPTION
**Pull request by vamsi-amazon**
### Description
Welcoming new maintianer @noCharger 

### Related Issues
Resolves #[Issue number to be closed when this PR is merged]

### Check List
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
 - [ ] New functionality has javadoc added.
 - [ ] New functionality has a user manual doc added.
- [ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md).
- [ ] Commits are signed per the DCO using `--signoff`.
- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose).

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/sql/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by dai-chen — APPROVED** [review]

**Review by ykmr1224 — APPROVED** [review]

**Comment by noCharger** [comment]
@opensearch-project/admin FYI

**Comment by gaiksaya** [comment]
Added @noCharger as the maintainer.
Looks like codeowners file is still invalid with below error:
```
Unknown owner on line 2: make sure @pjfitzgibbons exists and has write access to the repository
```
Please fix it. You can ask the maintainer if they still wish to be the maintainer. If yes, we can retain the access back else please consider moving them to emeritus section.
Thanks!

**Comment by noCharger** [comment]
> Added @noCharger as the maintainer. Looks like codeowners file is still invalid with below error:
> 
> ```
> Unknown owner on line 2: make sure @pjfitzgibbons exists and has write access to the repository
> ```
> 
> Please fix it. You can ask the maintainer if they still wish to be the maintainer. If yes, we can retain the access back else please consider moving them to emeritus section. Thanks!

Thanks, will create another PR to update it.

**Comment by peterzhuamazon** [comment]
Since it has been a long time since they moved.
You can move them to emeritus:
https://github.com/opensearch-project/.github/blob/main/RESPONSIBILITIES.md#removing-a-maintainer

**Pull request merged**
