### PR TITLE
Add 2.4 release note for SQL/PPL

### PR DESCRIPTION
**Pull request by dai-chen**
Signed-off-by: Chen Dai <daichen@amazon.com>

### Description
Add release note for OpenSearch 2.4 release.
 
### Issues Resolved
https://github.com/opensearch-project/sql/issues/905
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass, including unit test, integration test and doctest
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
  - [ ] New functionality has user manual doc added
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by joshuali925 — APPROVED** [review]

**Review by anirudha — APPROVED** [review]

**Comment by anirudha** [comment]
thanks

**Comment by dai-chen** [comment]
> Is it worth having there JDBC and ODBC related fixes?

Good question. I was thinking about the same. But because we're following this rule: https://github.com/opensearch-project/opensearch-plugins/blob/main/RELEASE_NOTES.md and meanwhile trying to separate JDBC/ODBC out of this repo. Probably it's fine we mix them together as before?

**Comment by Yury-Fridlyand** [comment]
Why not?
Maybe we can move them to a separate section of RN. I have no objections anyway.

**Comment by dai-chen** [comment]
> Why not? Maybe we can move them to a separate section of RN. I have no objections anyway.

Just discussed with @anirudha and we want to follow the current rule. Will discuss this topic in broader context with JDBC/ODBC separate release process and repository together. Thanks!

**Pull request merged**
