### PR TITLE
Reorganize development documentation

### PR DESCRIPTION
**Pull request by dai-chen**
Signed-off-by: Chen Dai <daichen@amazon.com>

### Description
TODO
 
### Issues Resolved
N/A
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass, including unit test, integration test and doctest
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
  - [ ] New functionality has user manual doc added
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by MaxKsyunz — COMMENTED** [review]
@dai-chen where did the content in `expression-pushdown.md` originate?
It looks like it was written before V2 engine was added.

**Comment by dai-chen** [comment]
> @dai-chen where did the content in `expression-pushdown.md` originate? It looks like it was written before V2 engine was added.

Hi @MaxKsyunz It is part of the V2 engine from internal design documentation. I'm trying to make this kind of doc public in this PR as well.

**Comment by MaxKsyunz** [comment]
> > @dai-chen where did the content in `expression-pushdown.md` originate? It looks like it was written before V2 engine was added.
> 
> Hi @MaxKsyunz It is part of the V2 engine from internal design documentation. I'm trying to make this kind of doc public in this PR as well.

Much appreciated @dai-chen. Thank you!

**Comment by dai-chen** [comment]
Default branch was changed. Will raise new PR after rebase.

**Pull request closed without merging**
