### PR TITLE
[Backport main] Bump jackson to 2.14.0 (#1058)

### LINKED ISSUE #1065: [AUTOCUT] OS Distribution Build Failed for sql-3.0.0
***Received Error***: **Error building sql, retry with: ./build.sh manifests/3.0.0/opensearch-3.0.0.yml --component sql**.
                      The distribution build for sql has failed.
                      Please see build log at https://build.ci.opensearch.org/job/distribution-build-opensearch/6445/consoleFull

### PR DESCRIPTION
**Pull request by Yury-Fridlyand**
Signed-off-by: Joshua Li <joshuali925@gmail.com>
(cherry picked from commit 5a1adb236f5589dfd10aa17783f13684b70a3c51)
Signed-off-by: Yury-Fridlyand <yuryf@bitquilltech.com>

### Description
Backport #1058 to `main`.
 
### Issues Resolved
Fixes #1065
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass, including unit test, integration test and doctest
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
  - [ ] New functionality has user manual doc added
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by joshuali925** [comment]
not sure what this is, checking

```
> Task :integ-test:test FAILED
Error occurred during initialization of VM
java.lang.Error: Could not create SecurityManager
	at java.lang.System.initPhase3(java.base@11.0.16.1/System.java:2065)
Caused by: java.lang.ClassNotFoundException: allow
	at jdk.internal.loader.BuiltinClassLoader.loadClass(java.base@11.0.16.1/BuiltinClassLoader.java:581)
```

**Comment by joshuali925** [comment]
upstream issue https://github.com/opensearch-project/opensearch-build/issues/2886

**Review by MitchellGale-BitQuill — APPROVED** [review]

**Comment by penghuo** [comment]
could we close this PR? main using 2.14.1 now, and will auto sync with OpenSearch core in future. https://github.com/opensearch-project/sql/pull/1169

**Comment by Yury-Fridlyand** [comment]
Ok

**Pull request closed without merging**
