### PR TITLE
[Backport 2.x] Modified returning NaN to NULL

### PR DESCRIPTION
**Pull request by GumpacG**
Signed-off-by: Guian Gumpac <guian.gumpac@improving.com>
(cherry picked from commit de40f4284ec428e1d24fc1112cce7fdfb7c1d787) from https://github.com/opensearch-project/sql/pull/1341

 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass, including unit test, integration test and doctest
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
  - [ ] New functionality has user manual doc added
- [ ] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by acarbonetto — APPROVED** [review]

**Review by Yury-Fridlyand — CHANGES_REQUESTED** [review]
Compilation fails

**Comment by GumpacG** [comment]
Compilation is failing due to dependency on https://github.com/opensearch-project/sql/pull/1348. Will rebase once PR 1348 is merged.

**Comment by Yury-Fridlyand** [comment]
@GumpacG try to rebase now.

**Comment by GumpacG** [comment]
@Yury-Fridlyand should be good now

**Review by Yury-Fridlyand — APPROVED** [review]

**Review by dai-chen — APPROVED** [review]

**Pull request merged**
