### PR TITLE
[Backport 2.18] Fix a regression issue of parsing datetime string with custom time format in Span (#3079)

### PR DESCRIPTION
**Pull request by LantaoJin**
(cherry picked from commit 4ff1fe3cb48a17ff17b0cf134131283fc0282205)

### CODE REVIEW

**Review by ykmr1224 — APPROVED** [review]

**Review by ykmr1224 — CHANGES_REQUESTED** [review]
CI is failing due to coverage.

**Comment by LantaoJin** [comment]
> CI is failing due to coverage.

done

**Comment by LantaoJin** [comment]
@ykmr1224 @dai-chen @YANG-DB @penghuo @seankao-az is this patch available to present in 2.18.0? or only in 2.18.1?

**Review by Swiddis — APPROVED** [review]

**Comment by LantaoJin** [comment]
Close this since the merging is blocked by requested changes from maintainer without subsequent approval.

**Pull request closed without merging**
