### PR TITLE
Add valueOf() to Expression

### LINKED ISSUE #976: Refactor ExprValue so valueEnv is not required
https://github.com/opensearch-project/sql/pull/949#discussion_r1005971116

Sometimes valueEnv is not required to resolve expression, but current implementation requires valueEnv. It's better to overload as `expr.valueOf()` instead of `expr.valueOf(null)`

### PR DESCRIPTION
**Pull request by joshuali925**
Signed-off-by: Joshua Li <joshuali925@gmail.com>

### Description
Minor change to use `valueOf()` instead of `valueOf(null)`
 
### Issues Resolved
closes #976 
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass, including unit test, integration test and doctest
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
  - [ ] New functionality has user manual doc added
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by derek-ho — APPROVED** [review]
LGTM

**Review by Yury-Fridlyand — APPROVED** [review]

**Review by Yury-Fridlyand — COMMENTED** [review]
Missing:
* `QueryRangeFunctionImplementation::valueOf` and its calls
* `QueryRangeFunctionImplementation::buildQueryFromQueryRangeFunction`
* `TimeRangeParametersResolver::visitFunction`

**Comment by joshuali925** [comment]
> Missing:
> 
> * `QueryRangeFunctionImplementation::valueOf` and its calls
> * `QueryRangeFunctionImplementation::buildQueryFromQueryRangeFunction`
> * `TimeRangeParametersResolver::visitFunction`

Thanks, i forgot i git ignored /prometheus directory.. updated PR

**Review by Yury-Fridlyand — APPROVED** [review]

**Review by vamsi-amazon — APPROVED** [review]

**Review by dai-chen — APPROVED** [review]
Thanks for refactoring this!

**Pull request merged**
