### PR TITLE
Bump Checkstyle version to latest

### PR DESCRIPTION
**Pull request by dai-chen**
Signed-off-by: Chen Dai <daichen@amazon.com>

### Description
1. Bump checkstyle from 8.28 to the latest version and fixed all violations.
2. Change `subprojects` to `allprojects` to enforce root project using same version as subproject (specified by `toolVersion`). Otherwise, the default Checkstyle version (8.37) defined by Gradle is in use.

```
$ ./gradlew dependencies :sql:dependencies :ppl:dependencies :core:dependencies :protocol:dependencies :opensearch-sql-plugin:dependencies :opensearch:dependencies :legacy:dependencies :common:dependencies | grep checkstyle
checkstyle - The Checkstyle libraries to be used for this project.
\--- com.puppycrawl.tools:checkstyle:10.3.2
checkstyle - The Checkstyle libraries to be used for this project.
\--- com.puppycrawl.tools:checkstyle:10.3.2
checkstyle - The Checkstyle libraries to be used for this project.
\--- com.puppycrawl.tools:checkstyle:10.3.2
checkstyle - The Checkstyle libraries to be used for this project.
\--- com.puppycrawl.tools:checkstyle:10.3.2
checkstyle - The Checkstyle libraries to be used for this project.
\--- com.puppycrawl.tools:checkstyle:10.3.2
checkstyle - The Checkstyle libraries to be used for this project.
\--- com.puppycrawl.tools:checkstyle:10.3.2
checkstyle - The Checkstyle libraries to be used for this project.
\--- com.puppycrawl.tools:checkstyle:10.3.2
checkstyle - The Checkstyle libraries to be used for this project.
\--- com.puppycrawl.tools:checkstyle:10.3.2
checkstyle - The Checkstyle libraries to be used for this project.
\--- com.puppycrawl.tools:checkstyle:10.3.2

$ ./gradlew dependencies :sql:dependencies :ppl:dependencies :core:dependencies :protocol:dependencies :opensearch-sql-plugin:dependencies :opensearch:dependencies :legacy:dependencies :common:dependencies | grep guava | grep 28

```
 
### Issues Resolved
https://github.com/opensearch-project/sql/issues/431
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass, including unit test, integration test and doctest
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
  - [ ] New functionality has user manual doc added
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by Yury-Fridlyand** [comment]
Are you planning to activate checkstyle for `:protocol`, `:integ-test` and `:plugin`?

**Comment by dai-chen** [comment]
> Are you planning to activate checkstyle for `:protocol`, `:integ-test` and `:plugin`?

I think Checkstyle has been activated for all our modules?

**Comment by Yury-Fridlyand** [comment]
Maybe it is activated, but
```
./gradlew :integ-test:checkstyleTest
...
Checkstyle files with violations: 55
Checkstyle violations by severity: [error:959]
...
BUILD SUCCESSFUL in 1m 11s
```
All 959 errors are ignored/suppressed.

**Comment by dai-chen** [comment]
> 

`checkstyleTest.ignoreFailures = true` in `integ-test` because of many IT code is from legacy engine. Are you suggesting to enable it? Sorry, I didn't get your concern in your previous comment.

**Comment by Yury-Fridlyand** [comment]
Oh, I see. Just curious whether we need this in integration tests.

**Comment by dai-chen** [comment]
> Oh, I see. Just curious whether we need this in integration tests.

Got it. I guess it has been disabled because there were too many IT code from legacy engine when we migrate. Probably we should have only disabled it for `org.opensearch.sql.legacy` folder by adding it to `suppressions.xml`. Not sure if it's too late to do that now? :)

**Comment by Yury-Fridlyand** [comment]
`./gradlew :legacy:checkstyleMain :legacy:checkstyleTest` has no errors, these checks are enforced in `build` - that is confusing. Test code doesn't go to production, but all `checkstyleTest` (except integration) are enforced.
We can consider fixing this in scope of another task if it is needed and then activate it for `:integ-test`.

**Comment by dai-chen** [comment]
> `./gradlew :legacy:checkstyleMain :legacy:checkstyleTest` has no errors, these checks are enforced in `build` - that is confusing. Test code doesn't go to production, but all `checkstyleTest` (except integration) are enforced. We can consider fixing this in scope of another task if it is needed and then activate it for `:integ-test`.

I guess the reason you didn't see error is the entire `legacy` module is excluded in `suppressions.xml`: https://github.com/opensearch-project/sql/blob/main/config/checkstyle/suppressions.xml#L8

**Review by joshuali925 — APPROVED** [review]

**Review by penghuo — APPROVED** [review]

**Pull request merged**
