### PR TITLE
Function `str_to_date` should work with two-digits year

### PR DESCRIPTION
**Pull request by LantaoJin**
### Description
`str_to_date` function in https://opensearch.org/docs/latest/search-plugins/sql/functions/#date-and-time does not work with two-digits year ([RFC 822 date-time](http://www.w3.org/Protocols/rfc822/#z28) formatted). 

`SELECT str_to_date('23-Oct-17', '%d-%b-%y')` returns `0017-10-23`

With patching, above query returns `2017-10-23`.
 
### Issues Resolved
Resolves https://github.com/opensearch-project/sql/issues/2741
 
### Check List
- [x] New functionality includes testing.
  - [x] All tests pass, including unit test, integration test and doctest
- [-] New functionality has been documented.
  - [-] New functionality has javadoc added
  - [-] New functionality has user manual doc added
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by dai-chen — APPROVED** [review]
Thanks for the fix!

**Comment by YANG-DB** [comment]
@LantaoJin @dai-chen is this still relevant ?

**Review by YANG-DB — APPROVED** [review]

**Comment by LantaoJin** [comment]
> @LantaoJin @dai-chen is this still relevant ?

I think the issue is still existing. let me update to latest code base.

**Comment by LantaoJin** [comment]
CI failure not related. Merging

**Pull request merged**
