### PR TITLE
Support complex predicates for `IF` function in PPL

### PR DESCRIPTION
**Pull request by LantaoJin**
### Description
The predicate of function `if(predicate, arg1, arg2)` in PPL should support complex expression.
The current implementation only supports `TrueLiteral` and `FalseLiteral`, just like the example given in [doc](https://github.com/opensearch-project/sql/blob/7b40c2c6a1a83329a0805cb367a8a56f9fbe2c4b/docs/user/ppl/functions/condition.rst#if). Query such as `|eval test=if(pgs > 2, "yes", "no")` will fail with `"details": "Failed to parse query due to offending symbol [>] at:` 
 
This PR aims to support complex predicate expression, following cases will be supported:
- if(a > 2,  arg1, arg2)
- if(a != 2,  arg1, arg2)
- if(isnull(a),  arg1, arg2)
- if(not a>2,  arg1, arg2)
- if(not a in (0, 1), arg1, arg2)"
- if(not a in (0, 1) OR isnull(a), arg1, arg2)
- if(like(a, '_a%b%c_d_'), arg1, arg2)
- and more

### Issues Resolved
Resolves https://github.com/opensearch-project/sql/issues/2600 and https://github.com/opensearch-project/sql/issues/2653
 
### Check List
- [x] New functionality includes testing.
  - [x] All tests pass, including unit test, integration test and doctest
- [x] New functionality has been documented.
  - [x] New functionality has javadoc added
  - [x] New functionality has user manual doc added
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by penghuo — APPROVED** [review]
Thx!

**Review by dai-chen — DISMISSED** [review]
Thanks for the changes!

**Review by vamsi-amazon — DISMISSED** [review]

**Comment by LantaoJin** [comment]
None of current build issues caused by this PR.

**Comment by penghuo** [comment]
could u merge latest change from main and re-run test.

**Review by dai-chen — APPROVED** [review]

**Comment by LantaoJin** [comment]
Gently ping @penghuo @vamsi-amazon @YANG-DB

**Review by penghuo — APPROVED** [review]
Thx!

**Pull request merged**
