### PR TITLE
Bump version to 1.3.1

### PR DESCRIPTION
**Pull request by gaiksaya**
Signed-off-by: Sayali Gaikawad <gaiksaya@amazon.com>

### Description
Bump version to 1.3.1
 
### Issues Resolved
https://github.com/opensearch-project/opensearch-build/issues/1805
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass, including unit test, integration test and doctest
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
  - [ ] New functionality has user manual doc added
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by gaiksaya** [comment]
Hi @opensearch-project/sql  team, can someone look into the failing CI and let me know what more needs to change here?
Thanks!

**Comment by dai-chen** [comment]
```
2022-03-28T22:25:01.0633301Z | Exception in thread "main" java.lang.IllegalArgumentException: Plugin [opensearch-ml] was built for OpenSearch version 1.3.0 but version 1.3.1 is running
2022-03-28T22:25:01.0633956Z | 	at org.opensearch.plugins.PluginsService.verifyCompatibility(PluginsService.java:392)
2022-03-28T22:25:01.0634612Z | 	at org.opensearch.plugins.InstallPluginCommand.loadPluginInfo(InstallPluginCommand.java:815)
2022-03-28T22:25:01.0635278Z | 	at org.opensearch.plugins.InstallPluginCommand.installPlugin(InstallPluginCommand.java:870)
2022-03-28T22:25:01.0635914Z | 	at org.opensearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:275)
2022-03-28T22:25:01.0636507Z | 	at org.opensearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:249)
2022-03-28T22:25:01.0637112Z | 	at org.opensearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:100)
2022-03-28T22:25:01.0637689Z | 	at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:138)
2022-03-28T22:25:01.0638209Z | 	at org.opensearch.cli.MultiCommand.execute(MultiCommand.java:104)
2022-03-28T22:25:01.0638714Z | 	at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:138)
2022-03-28T22:25:01.0639194Z | 	at org.opensearch.cli.Command.main(Command.java:101)
2022-03-28T22:25:01.0639637Z | 	at org.opensearch.plugins.PluginCli.main(PluginCli.java:60)
```

Need to bump dependency plugin version as well?

**Comment by gaiksaya** [comment]
> opensearch-ml

Missed it. Bumped it now.

**Comment by dai-chen** [comment]
It seems the same opensearch-ml-client error. Could we refer to other repo and check if any change missed? Or ask help from ML client owner?

**Comment by joshuali925** [comment]
`doctest/resources/ml-commons/opensearch-ml-1.3.0.0-SNAPSHOT.zip`
this also needs to be 1.3.1?

**Comment by gaiksaya** [comment]
Thanks for the help @dai-chen and @joshuali925 . Please review since all tests have passed.

**Review by joshuali925 — APPROVED** [review]
lgtm, thanks

**Review by dai-chen — APPROVED** [review]
Thanks for the changes!

**Pull request merged**
