### PR TITLE
adding reflections as a dependency

### PR DESCRIPTION
**Pull request by dhrubo-os**
### Description
adding reflections as a dependency.

```
POST _plugins/_ppl
{
  "query": "source=iris_data | fields petal_length_in_cm,petal_width_in_cm | kmeans centroids=3"
}
```

This command was breaking and the debug log is:

```
Caused by: java.lang.NoClassDefFoundError: org/reflections/Reflections
opensearch-node1         | 	at org.opensearch.ml.common.MLCommonsClassLoader.loadMLAlgoParameterClassMapping(MLCommonsClassLoader.java:66) ~[?:?]
opensearch-node1         | 	at org.opensearch.ml.common.MLCommonsClassLoader.loadClassMapping(MLCommonsClassLoader.java:51) ~[?:?]
opensearch-node1         | 	at org.opensearch.ml.common.MLCommonsClassLoader.lambda$static$0(MLCommonsClassLoader.java:39) ~[?:?]
opensearch-node1         | 	at java.security.AccessController.doPrivileged(AccessController.java:569) ~[?:?]
opensearch-node1         | 	at org.opensearch.ml.common.MLCommonsClassLoader.<clinit>(MLCommonsClassLoader.java:38) ~[?:?]
opensearch-node1         | 	at org.opensearch.ml.common.output.MLOutput.fromStream(MLOutput.java:35) ~[?:?]
opensearch-node1         | 	at org.opensearch.ml.common.transport.MLTaskResponse.<init>(MLTaskResponse.java:38) ~[?:?]
opensearch-node1         | 	at org.opensearch.ml.common.transport.MLTaskResponse.fromActionResponse(MLTaskResponse.java:55) ~[?:?]
opensearch-node1         | 	at org.opensearch.ml.client.MachineLearningNodeClient.lambda$getMlPredictionTaskResponseActionListener$8(MachineLearningNodeClient.java:191) 
```

 
### Issues Resolved
[List any issues this PR will resolve]
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass, including unit test, integration test and doctest
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
  - [ ] New functionality has user manual doc added
- [ ] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by dai-chen** [comment]
Is this issue only for 2.x? If not, normally we send PR to `main` branch first.

**Comment by dhrubo-os** [comment]
> Is this issue only for 2.x? If not, normally we send PR to `main` branch first.

Yeah we found this issue in 2.7. Should I raise a PR for `main` branch?

**Comment by dhrubo-os** [comment]
Raised a PR for main branch: https://github.com/opensearch-project/sql/pull/1559

**Comment by Yury-Fridlyand** [comment]
Could you please add integration test?

**Comment by ylwu-amzn** [comment]
> Could you please add integration test?

Thanks @Yury-Fridlyand , good point. I think it takes effort to do that. Considering this issue blocks OS2.7 release and we have verified manually this PR will fix the issue, how about we merge this PR first? We can continuously improving the integ testing.

**Comment by dai-chen** [comment]
Closing as duplicate https://github.com/opensearch-project/sql/pull/1559

**Pull request closed without merging**
