### PR TITLE
Call LeaseManager for BatchQuery

### PR DESCRIPTION
**Pull request by ykmr1224**
### Description
- Call LeaseManager for BatchQuery
  - Currently, LeaseManager.borrow is not called for BatchQuery

### Related Issues
n/a

### Check List
- [x] New functionality includes testing.
- [ ] New functionality has been documented.
 - [ ] New functionality has javadoc added.
 - [ ] New functionality has a user manual doc added.
- [ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md).
- [x] Commits are signed per the DCO using `--signoff`.
- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose).

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/sql/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by ykmr1224** [comment]
CI failure is due to coverage caused by: https://github.com/opensearch-project/sql/pull/3063

**Review by noCharger — COMMENTED** [review]
High level questions

1. Does the current class model meet the requirements for extending to another implementation?

https://github.com/opensearch-project/sql/blob/cfe38d7d6678dfbd5597f1098a1a47e29f84a708/async-query/src/main/java/org/opensearch/sql/spark/transport/config/AsyncExecutorServiceModule.java#L230-L232

2. Will this code change to BatchQueryHandler and RefreshQueryHandler affect the present logic of examining ConcurrentRefreshJobRule?

**Comment by ykmr1224** [comment]
> 1. Does the current class model meet the requirements for extending to another implementation?
> 
> https://github.com/opensearch-project/sql/blob/cfe38d7d6678dfbd5597f1098a1a47e29f84a708/async-query/src/main/java/org/opensearch/sql/spark/transport/config/AsyncExecutorServiceModule.java#L230-L232
> 

Yes, DQS will internally check running jobs and limit new execution.

> 2. Will this code change to BatchQueryHandler and RefreshQueryHandler affect the present logic of examining ConcurrentRefreshJobRule?

It won't affect. I excluded Batch query from ConcurrentRefreshJobRule.

**Review by noCharger — APPROVED** [review]

**Comment by ykmr1224** [comment]
> Could you elaborate a little what was the issue?

DQS couldn't cover the Batch query to avoid too many concurrent execution.

**Pull request merged**
