### PR TITLE
Set baseline JDK version to JDK-21

### PR DESCRIPTION
**Pull request by manasvinibs**
### Description
Sets the baseline JDK version to JDK-21
 
### Issues Resolved
https://github.com/opensearch-project/sql/issues/2713

### CODE REVIEW

**Comment by noCharger** [comment]
let's fix CI and security check, thanks!

**Comment by manasvinibs** [comment]
> let's fix CI and security check, thanks!

Looks like Whitesource security check scanner has failed to scan the repo and seems unrelated to this change. 

For BWC test failure here https://github.com/opensearch-project/sql/actions/runs/9719035598/job/26828118379?pr=2787

I see below error 
```
Execution failed for task ':integ-test:sqlBwcCluster#mixedClusterTask'.
> `cluster{:integ-test:sqlBwcCluster0}` failed to wait for cluster health yellow after 40 SECONDS
    IO error while waiting cluster
    503 Service Unavailable
```
which also seems to be not related to the upgrade change. Can you help me understand how can I fix this if it is related to my change?

**Comment by ykmr1224** [comment]
I saw similar bwc test failure before, and @derek-ho fixed that in https://github.com/opensearch-project/sql/pull/2662
I think it was partially caused by version mismatch with ml-commons plugin

**Comment by noCharger** [comment]
> > let's fix CI and security check, thanks!
> 
> Looks like Whitesource security check scanner has failed to scan the repo and seems unrelated to this change.
> 
> For BWC test failure here https://github.com/opensearch-project/sql/actions/runs/9719035598/job/26828118379?pr=2787
> 
> I see below error
> 
> ```
> Execution failed for task ':integ-test:sqlBwcCluster#mixedClusterTask'.
> > `cluster{:integ-test:sqlBwcCluster0}` failed to wait for cluster health yellow after 40 SECONDS
>     IO error while waiting cluster
>     503 Service Unavailable
> ```
> 
> which also seems to be not related to the upgrade change. Can you help me understand how can I fix this if it is related to my change?

Could you rerun whitesource? As per the CI, could you try `:integ-test:sqlBwcCluster#mixedClusterTask` locally?

**Comment by manasvinibs** [comment]
> > > let's fix CI and security check, thanks!
> > 
> > 
> > Looks like Whitesource security check scanner has failed to scan the repo and seems unrelated to this change.
> > For BWC test failure here https://github.com/opensearch-project/sql/actions/runs/9719035598/job/26828118379?pr=2787
> > I see below error
> > ```
> > Execution failed for task ':integ-test:sqlBwcCluster#mixedClusterTask'.
> > > `cluster{:integ-test:sqlBwcCluster0}` failed to wait for cluster health yellow after 40 SECONDS
> >     IO error while waiting cluster
> >     503 Service Unavailable
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > which also seems to be not related to the upgrade change. Can you help me understand how can I fix this if it is related to my change?
> 
> Could you rerun whitesource? As per the CI, could you try `:integ-test:sqlBwcCluster#mixedClusterTask` locally?

Yes in local I see this error

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':integ-test:sqlBwcCluster#oldVersionClusterTask0'.
> Could not resolve all files for configuration ':integ-test:opensearch_distro_extracted_testclusters-integ-test-sqlBwcCluster0-0-2.15.0-'.
   > Could not resolve opensearch-distribution:opensearch:2.15.0.
     Required by:
         project :integ-test
      > Could not resolve opensearch-distribution:opensearch:2.15.0.
         > Could not get resource 'https://artifacts.opensearch.org/releases/core/opensearch/2.15.0/opensearch-min-2.15.0-darwin-x64.tar.gz'.
            > Could not HEAD 'https://artifacts.opensearch.org/releases/core/opensearch/2.15.0/opensearch-min-2.15.0-darwin-x64.tar.gz'. Received status code 403 from server: Forbidden
      > Could not resolve opensearch-distribution:opensearch:2.15.0.
         > Could not get resource 'https://artifacts.opensearch.org/release-candidates/core/opensearch/2.15.0/opensearch-min-2.15.0-darwin-x64.tar.gz'.
            > Could not HEAD 'https://artifacts.opensearch.org/release-candidates/core/opensearch/2.15.0/opensearch-min-2.15.0-darwin-x64.tar.gz'. Received status code 403 from server: Forbidden

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.4/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.

BUILD FAILED in 2s
```
Similar to Derek's PR, this seems to be related to not finding the artifacts for Darwin x64 platform.

**Comment by manasvinibs** [comment]
@peterzhuamazon Hi Peter, we are having BWC test failures in our CI because of not finding Darwin artifacts for 2.15. Is this known issue?

**Comment by penghuo** [comment]
> @peterzhuamazon Hi Peter, we are having BWC test failures in our CI because of not finding Darwin artifacts for 2.15. Is this known issue?

Test is on Linux, not related MacOS

Should we bump String baseVersion = "2.15.0" to 2.16.0 now?

**Comment by penghuo** [comment]
Depend on https://github.com/opensearch-project/sql/pull/2743

**Comment by derek-ho** [comment]
> > @peterzhuamazon Hi Peter, we are having BWC test failures in our CI because of not finding Darwin artifacts for 2.15. Is this known issue?
> 
> Test is on Linux, not related MacOS
> 
> Should we bump String baseVersion = "2.15.0" to 2.16.0 now?

Yes the base version should be bumped

**Review by derek-ho — APPROVED** [review]

**Review by penghuo — APPROVED** [review]
Thx!

**Comment by dai-chen** [comment]
@manasvinibs This PR incorporates many changes in ANTLR grammar automatically. Can we backport this `2.x` branch?

If concern, I think we need to create a PR manually with only grammar changes. Otherwise, we may miss those changes in all 2.x release.

**Pull request merged**
