### PR TITLE
AD timefield name issue

### PR DESCRIPTION
**Pull request by jngz-es**
### Description
https://github.com/opensearch-project/ml-commons/issues/467
 
### Issues Resolved
[List any issues this PR will resolve]
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass, including unit test, integration test and doctest
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
  - [ ] New functionality has user manual doc added
- [ ] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by joshuali925 — DISMISSED** [review]

**Comment by joshuali925** [comment]
any tests on AD?

**Comment by jngz-es** [comment]
Looks like the existing UT doesn't cover the full project logic, I will rewrite it.

**Review by penghuo — DISMISSED** [review]
LGTM

**Review by MaxKsyunz — APPROVED** [review]
LGTM

**Review by joshuali925 — APPROVED** [review]
thanks!

**Review by penghuo — APPROVED** [review]

**Pull request merged**
