### PR TITLE
Incremented version to 2.1.1.

### PR DESCRIPTION
**Pull request by gaiksaya**
Coming from https://github.com/opensearch-project/opensearch-build/issues/1818 post release activities.

### CODE REVIEW

**Comment by penghuo** [comment]
Pending on org.opensearch:opensearch-ml-client:2.1.1.0-SNAPSHOT release

**Comment by gaiksaya** [comment]
> Pending on org.opensearch:opensearch-ml-client:2.1.1.0-SNAPSHOT release

I see it here https://aws.oss.sonatype.org/content/repositories/snapshots/org/opensearch/opensearch-ml-client/2.1.0.0-SNAPSHOT/

**Comment by joshuali925** [comment]
there is still no org.opensearch:opensearch-ml-client:2.1.1.0-SNAPSHOT? 
https://aws.oss.sonatype.org/content/repositories/snapshots/org/opensearch/opensearch-ml-client/2.1.1.0-SNAPSHOT/

**Comment by gaiksaya** [comment]
Closing this as 2.2.0 is released and this version will not be out now.
Thanks!

**Pull request closed without merging**
