### PR TITLE
Fix incorrect results returned by `min`, `max` and `avg`

### LINKED ISSUE #817: [BUG] Aggregation functions return invalid result when processing NULLs
I use [TDVT data set](https://github.com/tableau/connector-plugin-sdk/blob/master/tests/datasets/TestV1/Calcs_headers.csv) for experiments
<details>
<summary>dataset</summary>

```
opensearchsql> select int0 i0, int1 i1, int2 from calcs;
fetched rows / total rows = 17/17
+------+------+--------+
| i0   | i1   | int2   |
|------+------+--------|
| 1    | -3   | 5      |
| null | -6   | -4     |
| null | null | 5      |
| null | -4   | -5     |
| 7    | null | 3      |
| 3    | null | 2      |
| 8    | null | 9      |
| null | 2    | 0      |
| null | 3    | -6     |
| 8    | 3    | -9     |
| 4    | null | -3     |
| 10   | -8   | -4     |
| null | null | 0      |
| 4    | null | 4      |
| 11   | null | -8     |
| 4    | null | -9     |
| 8    | -9   | 6      |
+------+------+--------+
```
</details>

The test query:
```sql
select max(int0), int1, min(int2) from calcs group by int1;
```
OpenSearch:
```
opensearchsql> select max(`int0`), `int1`, min(`int2`) from calcs group by `int1`;
fetched rows / total rows = 8/8
+---------------+--------+---------------+
| max(`int0`)   | int1   | min(`int2`)   |
|---------------+--------+---------------|
| 11            | null   | -9            |
| 8             | -9     | 6             |
| 10            | -8     | -4            |
| -2147483648   | -6     | -4            |
| -2147483648   | -4     | -5            |
| 1             | -3     | 5             |
| -2147483648   | 2      | 0             |
| 8             | 3      | -9            |
+---------------+--------+---------------+
```
MySQL:
```
mysql> select max(`int0`), `int1`, min(`int2`) from Calcs group by `int1`;
+-------------+------+-------------+
| max(`int0`) | int1 | min(`int2`) |
+-------------+------+-------------+
|           1 |   -3 |           5 |
|        NULL |   -6 |          -4 |
|          11 | NULL |          -9 |
|        NULL |   -4 |          -5 |
|        NULL |    2 |           0 |
|           8 |    3 |          -9 |
|          10 |   -8 |          -4 |
|           8 |   -9 |           6 |
+-------------+------+-------------+
8 rows in set (0.00 sec)
```

See also (could be related):
- [ ] https://github.com/opensearch-project/sql/issues/549
- [ ] https://github.com/opensearch-project/sql/issues/645
- [ ] https://github.com/opensearch-project/sql/issues/799
- [ ] https://github.com/opensearch-project/sql/issues/279
- [ ] https://github.com/opensearch-project/sql/issues/258
- [ ] https://github.com/opensearch-project/sql/issues/124

### PR DESCRIPTION
**Pull request by Yury-Fridlyand**
Fix incorrect results returned by `min`, `max` and `avg` when processing null/missing values only.

Signed-off-by: Yury-Fridlyand <yuryf@bitquilltech.com>

See team review & discussion in https://github.com/Bit-Quill/opensearch-project-sql/pull/145

### Description
**Before**
```
opensearchsql> select min(int0) from calcs where int0 IS NULL;
fetched rows / total rows = 1/1
+-------------+
| min(int0)   |
|-------------|
| 2147483647  |
+-------------+
```
**After**
```
opensearchsql> select min(int0) from calcs where int0 IS NULL;
fetched rows / total rows = 1/1
+-------------+
| min(int0)   |
|-------------|
| null        |
+-------------+
```
### Fixed:
* `min`
* `max`
* `avg`

### Not fixed:
* `sum`
```
opensearchsql> select sum(int0) from calcs where int0 IS NULL;
fetched rows / total rows = 1/1
+-------------+
| sum(int0)   |
|-------------|
| 0           |
+-------------+
```
```
mysql> select sum(int0) from calcs where int0 IS NULL;

+-----------+
| sum(int0) |
+-----------+
|      NULL |
+-----------+
1 row in set (0.00 sec)
```
This requires much more changes.

### Not affected
* `var_samp`
* `var_pop`
* `stddev_samp`
* `stddev_pop`
 
### Issues Resolved
Fixes #817
 
### Check List
- [x] New functionality includes testing.
  - [x] All tests pass, including unit test, integration test and doctest
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
  - [ ] New functionality has user manual doc added
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by MaxKsyunz — APPROVED** [review]

**Review by penghuo — DISMISSED** [review]
Thanks.

**Comment by dai-chen** [comment]
The CodeQL is failing and seems caused by some regular expression in GrokUtils. I assume it's introduced by other PR earlier? https://github.com/opensearch-project/sql/pull/1000/checks?check_run_id=9215922956

**Comment by Yury-Fridlyand** [comment]
> The CodeQL is failing and seems caused by some regular expression in GrokUtils. I assume it's introduced by other PR earlier? https://github.com/opensearch-project/sql/pull/1000/checks?check_run_id=9215922956

Yes, see #889, introduced in #813.

**Comment by dai-chen** [comment]
> > The CodeQL is failing and seems caused by some regular expression in GrokUtils. I assume it's introduced by other PR earlier? https://github.com/opensearch-project/sql/pull/1000/checks?check_run_id=9215922956
> 
> Yes, see #889, introduced in #813.

I see. Not sure why it doesn't fail on all other PRs.

Btw, to follow the same procedure, should we choose 2.x branch as target and label with `backport 2.4`

**Comment by Yury-Fridlyand** [comment]
Done. Please, re-review.

**Comment by dai-chen** [comment]
> Done. Please, re-review.

Looks good. Thanks!

**Review by dai-chen — APPROVED** [review]

**Review by MaxKsyunz — APPROVED** [review]

**Pull request merged**
