### PR TITLE
Bumps version to 1.2

### PR DESCRIPTION
**Pull request by Tengda-He**
Signed-off-by: Tengda He <tengh@amazon.com>

### Description
Updates dashbquery-workbench-dashboardsoards version to 1.2. Changes the package jsons, as well as the github action workflows.
 
### Issues Related
#214 

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass, including unit test, integration test and doctest
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
  - [ ] New functionality has user manual doc added
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by chloe-zh** [comment]
Hi @Tengda-He is this PR only to bump version for dashboards and dashboards plugin? 

I think some of the plugins and files are missed for version bump, could you refer to this PR https://github.com/opensearch-project/sql/pull/253 thanks!

**Comment by Tengda-He** [comment]
Hi Chloe, thanks for the heads up. Yes, we want the plugin team to bump version to 1.2 to unblock OSD 1.2 bundle build process.

This task is assigned to plugin team to own, if there are many other files also need to change, can plugin team help with this task? as the domain expert on this. Thanks

**Comment by joshuali925** [comment]
I see these are still not bumped, I'll update your PR to bump them
https://github.com/opensearch-project/sql/blob/927ccb1ded5b6a1b828086d165030a5dcbfb9b2e/.github/workflows/sql-test-and-build-workflow.yml#L19
https://github.com/opensearch-project/sql/blob/927ccb1ded5b6a1b828086d165030a5dcbfb9b2e/sql-jdbc/build.gradle#L46

**Comment by kavithacm** [comment]
There are some more changes to be made, so i'll make those changes and push to this branch to update this PR

**Review by chloe-zh — APPROVED** [review]

**Pull request merged**
