### PR TITLE
Resolve Alias Issues in Legacy SQL with Filters

### LINKED ISSUE #2912: [BUG] Pagination of index aliases is not supported - Re-opened
Hi guys, I am re-opening this ticket that was opened a long time ago by MaxKsyunz reporting a bug using filter in aliases

https://github.com/opensearch-project/sql/issues/1398

It is possible to take a look? I have checked that in the latest version (2.15.0) the issues still happening using **filter in query using sql plugin to an alias**

If you remove the filter everything looks fine.

### PR DESCRIPTION
**Pull request by aparajita31pandey**
### Description
Alias query in legacy SQL  which had filters to it didn't work . This diff addresses that issue. This diff derives index name from alias, for  legacy sql queries having filters to it. 
 
Before the change
```
curl -X POST "localhost:9200/_plugins/_sql" -H 'Content-Type: application/json' -d '{
  "query": "SELECT * FROM my-alias",
  "fetch_size": 1,
   "filter" : {
    "term" : {
      "field2" : "Sample keyword2"
    }
  }
}'
{
  "error": {
    "reason": "There was internal problem at backend",
    "details": "Index type [my-alias] does not exist",
    "type": "IllegalArgumentException"
  },
  "status": 500
}
```
After the change: 
```
curl -X POST "localhost:9200/_plugins/_sql" -H 'Content-Type: application/json' -d '{
  "query": "SELECT * FROM my-alias",
  "fetch_size": 1,
   "filter" : {
    "term" : {
      "another_field" : "hello"
    }
  }
}'
{
  "schema": [
    {
      "name": "new_field",
      "type": "text"
    },
    {
      "name": "another_field",
      "type": "keyword"
    }
  ],
  "total": 1,
  "datarows": [[
    "Some text",
    "hello"
  ]],
  "size": 1,
  "status": 200
```

### Related Issues
Resolves #2912 
#1398 #1412 

### Check List
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
 - [ ] New functionality has javadoc added.
 - [ ] New functionality has a user manual doc added.
- [ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md).
- [x] Commits are signed per the DCO using `--signoff`.
- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose).

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/sql/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by ctellechea2001** [comment]
@aparajita31pandey Do you know when could be this PR reviewed and merged to fix this issue that we have reported?
https://github.com/opensearch-project/sql/issues/2912

**Comment by HabooshHaddad** [comment]
Hello ,
I this going to be merged anytime soon ?

**Comment by LantaoJin** [comment]
Thanks for your contribution, @aparajita31pandey could you add an unit test for the changes?

**Comment by aparajita31pandey** [comment]
@LantaoJin I have tested and added an IntegTest for the changes. Please take a look

**Review by LantaoJin — APPROVED** [review]

**Comment by aparajita31pandey** [comment]
@LantaoJin  Updated the diff with ` ./gradlew spotlessApply`

**Review by LantaoJin — APPROVED** [review]
The build failure is irrelevant, LGTM

**Comment by aparajita31pandey** [comment]
@dai-chen  @ykmr1224  Can I get one more approval please?

**Comment by aparajita31pandey** [comment]
Hey @LantaoJin , can you please help getting this diff merged ?

**Comment by ctellechea2001** [comment]
@LantaoJin Do you know in which open-search release version will be included? Thanks a lot!.

**Comment by cwperks** [comment]
@aparajita31pandey FYI we are seeing an issue similar to https://github.com/opensearch-project/security/issues/5871

I think we should revisit this PR because I suspect alias resolution may have been working as expected. 

In this block in particular:

```
Map<String, Map<String, FieldMappingMetadata>> mappings = response.mappings();
if (mappings.isEmpty() || !mappings.containsKey(indexName)) {
  throw new IllegalArgumentException(
      String.format("Index type %s does not exist", query.getFrom()));
}
```

We check if the indexName that we supplied in the GetFieldMappingRequest is also in the response, but with an alias we can supply an alias in the request and the mappings response would have concrete index.

For example in an automated test I wrote I got the following:

```
> GET my_alias/_mapping/field/field

{"concrete_index":{"mappings":{"field":{"full_name":"field","mapping":{"field":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}}}}}}}
```

so `my_alias` was supplied in the request and the response had `concrete_index`

Do you think we can simply change the block to this:

```
Map<String, Map<String, FieldMappingMetadata>> mappings = response.mappings();
// only check if response is empty
if (mappings.isEmpty()) {
  throw new IllegalArgumentException(
      String.format("Index type %s does not exist", query.getFrom()));
}
```

**Comment by aparajita31pandey** [comment]
@cwperks Thanks for pointing this out. I have made some refactoring changes [here](https://github.com/opensearch-project/sql/pull/4981/). Do you know of any cases where FieldMappings for an index or alias would return multiple results?

**Comment by cwperks** [comment]
> @cwperks Thanks for pointing this out. I have made some refactoring changes [here](https://github.com/opensearch-project/sql/pull/4981/). Do you know of any cases where FieldMappings for an index or alias would return multiple results?

alias <-> index is not one-to-one. I think you can have an alias map to multiple concrete indices.

**Pull request merged**
