### PR TITLE
Incremented version to 1.3.2.

### PR DESCRIPTION
**Pull request by gaiksaya**
Signed-off-by: Sayali Rohidas Gaikawad <gaiksaya@amazon.com>

Coming from https://github.com/opensearch-project/opensearch-build/issues/1805 post release activity.
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass, including unit test, integration test and doctest
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
  - [ ] New functionality has user manual doc added
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by joshuali925 — APPROVED** [review]

**Comment by dai-chen** [comment]
SQL CI failed?

**Comment by gaiksaya** [comment]
> SQL CI failed?

Yes looks like it is not able to find the ml-client. Any idea how to resolve this?
Thanks!

**Review by kavithacm — APPROVED** [review]

**Comment by penghuo** [comment]
@gaiksaya should we close this PR in case 1.3.2 already in there.
https://github.com/opensearch-project/sql/pull/593

**Comment by joshuali925** [comment]
closing, duplicate of #593

**Pull request closed without merging**
