### PR TITLE
Escape character support for string literals

### PR DESCRIPTION
**Pull request by MitchellGale-BitQuill**
### Description
Adds support for escape characters `\` to be used to escape characters in string literals. Keeps support for double quote to act as an escape if the surrounding quote is matching type (single quote, or double quote).

```
SELECT "Hello", 'Hello', "It""s", 'It''s', "It's", '"Its"', 'It\'s', 'It\\\'s', "\I\t\s"
fetched rows / total rows = 1/1
+-----------+-----------+-----------+-----------+----------+-----------+-----------+-------------+------------+
| "Hello"   | 'Hello'   | "It""s"   | 'It''s'   | "It's"   | '"Its"'   | 'It\'s'   | 'It\\\'s'   | "\I\t\s"   |
|-----------+-----------+-----------+-----------+----------+-----------+-----------+-------------+------------|
| Hello     | Hello     | It"s      | It's      | It's     | "Its"     | It's      | It\'s       | \I\t\s     |
+-----------+-----------+-----------+-----------+----------+-----------+-----------+-------------+------------+
```

### Issues Resolved
https://github.com/opensearch-project/sql/issues/297
 
### Check List
- [X] New functionality includes testing.
  - [X] All tests pass, including unit test, integration test and doctest
- [x] New functionality has been documented.
  - [x] New functionality has javadoc added
  - [ ] New functionality has user manual doc added
- [X] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by Yury-Fridlyand** [comment]
Isn't a breaking change?

**Comment by acarbonetto** [comment]
> Isn't a breaking change?

Yes.  This should not be a backport change.

**Review by MaxKsyunz — APPROVED** [review]

**Comment by penghuo** [comment]
could you add more context about breacking change in PR. then during release stage, we can organice all the breaking changes in release notes.

**Comment by Yury-Fridlyand** [comment]
**1.** Add a test index:
```
curl -X POST "localhost:9200/dbg/_doc/?pretty" -H 'Content-Type: application/json' -d '{"someText": "\\1\\\\2\\\\\\3\\\\\\\\4\\\\\\\\\\5\\\\\\\\\\\\6"}'
```
(actually there are 1..6 backslashes, but they are escaped)

**2.** Run a query (without this fix):
```
opensearchsql> select * from dbg;
fetched rows / total rows = 1/1
+-----------------------------+
| someText                    |
|-----------------------------|
| \1\\2\\\3\\\\4\\\\\5\\\\\\6 |
+-----------------------------+
opensearchsql> select * from dbg where someText = "\1\\2\\\3\\\\4\\\\\5\\\\\\6";
fetched rows / total rows = 1/1
+-----------------------------+
| someText                    |
|-----------------------------|
| \1\\2\\\3\\\\4\\\\\5\\\\\\6 |
+-----------------------------+
opensearchsql> select * from dbg where someText = "\\1\\\\2\\\\\\3\\\\\\\\4\\\\\\\\\\5\\\\\\\\\\\\6";
fetched rows / total rows = 0/0
+------------+
| someText   |
|------------|
+------------+
```

**3.** Checkout this PR, build and install

**4.** Run the query again (with this fix):
```
opensearchsql> select * from dbg;
fetched rows / total rows = 1/1
+-----------------------------+
| someText                    |
|-----------------------------|
| \1\\2\\\3\\\\4\\\\\5\\\\\\6 |
+-----------------------------+
opensearchsql> select * from dbg where someText = "\1\\2\\\3\\\\4\\\\\5\\\\\\6";
fetched rows / total rows = 0/0
+------------+
| someText   |
|------------|
+------------+
opensearchsql> select * from dbg where someText = "\\1\\\\2\\\\\\3\\\\\\\\4\\\\\\\\\\5\\\\\\\\\\\\6";
fetched rows / total rows = 1/1
+-----------------------------+
| someText                    |
|-----------------------------|
| \1\\2\\\3\\\\4\\\\\5\\\\\\6 |
+-----------------------------+
```

**5.** Delete the index:
```
curl -XDELETE 'http://localhost:9200/dbg'
```


This PR affects how string literals processed only. Values are still returned as is, without processing escape sequences.

**Review by Yury-Fridlyand — APPROVED** [review]

**Review by penghuo — APPROVED** [review]

**Pull request merged**
