### PR TITLE
Update to Gradle 8.4

### PR DESCRIPTION
**Pull request by reta**
### Description
Update to Gradle 8.4
 
### Issues Resolved
Part of https://github.com/opensearch-project/OpenSearch/issues/10334
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass, including unit test, integration test and doctest
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
  - [ ] New functionality has user manual doc added
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by MaxKsyunz — APPROVED** [review]

**Review by dai-chen — APPROVED** [review]

**Comment by dai-chen** [comment]
I see another PR https://github.com/opensearch-project/sql/pull/2470. Are we targeting 8.4 or 8.5?

**Comment by reta** [comment]
I mean this change is sitting 2 moths in review, we could move to 8.5 after (but should be nobrainer)

**Review by vamsi-amazon — APPROVED** [review]

**Comment by vamsi-amazon** [comment]
@dai-chen  would you be able to re trigger CI checks?

**Comment by vamsi-amazon** [comment]
somehow I couldn't trigger CI again. I just created a draft PR by cherry-picking the commit.  We can follow the latest CI results here: https://github.com/opensearch-project/sql/pull/2472

**Comment by dai-chen** [comment]
same here. cannot rerun the failed CI...

**Comment by reta** [comment]
> same here. cannot rerun the failed CI...

Thanks @dai-chen  The maintainers should be able to rerun the jobs , I am wondering why it is not the case for this repository ...

**Comment by vamsi-amazon** [comment]
There are build failures here: https://github.com/opensearch-project/sql/pull/2472
We need to understand them before merging this PR.

**Comment by reta** [comment]
> We need to understand them before merging this PR.

Sadly, the plugin has issues with stability of checks, there is not a single pull request that has checks passed [1], the same applies to main branch [2] commits :(
 
[1] https://github.com/opensearch-project/sql/pulls 
[2] https://github.com/opensearch-project/sql/commits/main/

**Comment by vamsi-amazon** [comment]
Pretty much all the bugs seems to be unrelated to this PR.
https://github.com/opensearch-project/sql/pull/2472 I tested with multiple fixes and still the CI is not working. 
The fixes made till now are unrelated to the current PR and moreover the upgrade is necessary, so going ahead with the merge.  I think this upgrade is not required for 2.x

Thanks @reta

**Pull request merged**
