### PR TITLE
Update the README file and and a link to the iODBC

### PR DESCRIPTION
**Pull request by alinaliBQ**
- add a link to the iODBC Driver Manager so it is easier to navigate and install the driver manger

### Description
 add a link to the iODBC Driver Manager so it is easier to navigate and install the driver manger
 
### Issues Resolved
only clarify the documentation, no code changes or new functionality
 
### Check List
- [ ] New functionality includes testing.
  not applicable
  - [ ] All tests pass, including unit test, integration test and doctest
  not applicable
- [x] New functionality has been documented.
not applicable
  - [x] New functionality has javadoc added
  not applicable
  - [x] New functionality has user manual doc added
  not applicable
- [ ] Commits are signed per the DCO using --signoff 
not applicable

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).
Signed-off-by: Alina (Xi) Li <alinal@bitquilltech.com>

### CODE REVIEW

**Comment by joshuali925** [comment]
[DCO](https://github.com/opensearch-project/opensearch-plugins/blob/main/CONTRIBUTING.md#developer-certificate-of-origin) is missing (which is a line saying `Signed-off-by: name <email>` in your commit message), you can fix by

```
git commit --amend --no-edit --signoff
git push <your-fork> patch-1 --force
```

Could you update the PR to include DCO? thanks

**Comment by alinaliBQ** [comment]
> [DCO](https://github.com/opensearch-project/opensearch-plugins/blob/main/CONTRIBUTING.md#developer-certificate-of-origin) is missing (which is a line saying `Signed-off-by: name <email>` in your commit message), you can fix by
> 
> ```
> git commit --amend --no-edit --signoff
> git push <your-fork> patch-1 --force
> ```
> 
> Could you update the PR to include DCO? thanks

Yes I'll look into that

**Comment by alinaliBQ** [comment]
opps, my commit was done from GitHub, not a local fork repository. It is a little more complicated to fix. I'll close this PR for now and look into it again next time

**Comment by alinaliBQ** [comment]
I'll look to finalize this PR by the end of next week and hopefully today : )

**Review by joshuali925 — APPROVED** [review]
thanks!

**Review by ps48 — APPROVED** [review]

**Comment by alinaliBQ** [comment]
thank you both as well!

**Pull request merged**
