### PR TITLE
Enable hive support in spark application

### PR DESCRIPTION
**Pull request by rupal-bq**
### Description
- Added enableHiveSupport in SparkSession
- Set flint config in spark session
- Fix parsing error
 
### Issues Resolved
https://github.com/opensearch-project/sql/issues/1721
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass, including unit test, integration test and doctest
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
  - [ ] New functionality has user manual doc added
- [ ] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by penghuo — DISMISSED** [review]

**Comment by penghuo** [comment]
ignore all the IT. not related to this PR.

**Comment by Yury-Fridlyand** [comment]
You can rebase your branch to make CI pass

**Comment by rupal-bq** [comment]
bwc test failure is not related to this PR

**Review by anirudha — APPROVED** [review]

**Review by dai-chen — APPROVED** [review]
Thanks for the fix!

**Pull request merged**
